-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  full_name character varying NOT NULL,
  phone_number character varying NOT NULL,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city character varying NOT NULL,
  state character varying,
  zip_code character varying NOT NULL,
  country character varying NOT NULL DEFAULT 'Afghanistan'::character varying,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.attribute_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attribute_id uuid,
  value character varying NOT NULL,
  color_code character varying,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attribute_values_pkey PRIMARY KEY (id),
  CONSTRAINT attribute_values_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.attributes(id)
);
CREATE TABLE public.attributes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  type character varying NOT NULL DEFAULT 'text'::character varying,
  unit character varying,
  is_required boolean DEFAULT false,
  is_filterable boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attributes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  logo_url text,
  website_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT brands_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cart_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT carts_pkey PRIMARY KEY (id),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.categories_new (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  icon character varying,
  parent_id uuid,
  level integer NOT NULL DEFAULT 0,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  CONSTRAINT categories_new_pkey PRIMARY KEY (id),
  CONSTRAINT categories_new_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories_new(id)
);
CREATE TABLE public.category_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  title character varying NOT NULL,
  subtitle character varying,
  description text,
  image_url text,
  link_category_id uuid,
  background_color character varying DEFAULT '#ffffff'::character varying,
  text_color character varying DEFAULT '#000000'::character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  link_brand_id uuid,
  link_url text,
  link_type text CHECK (link_type = ANY (ARRAY['category'::text, 'brand'::text, 'url'::text, 'tag'::text])),
  CONSTRAINT category_banners_pkey PRIMARY KEY (id),
  CONSTRAINT category_banners_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_banners_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_banners_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.category_image_buttons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  image_url text NOT NULL,
  link_url character varying NOT NULL,
  link_type character varying NOT NULL CHECK (link_type::text = ANY (ARRAY['category'::character varying, 'brand'::character varying, 'custom'::character varying, 'tag'::character varying]::text[])),
  link_category_id uuid,
  link_brand_id uuid,
  link_tag character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT category_image_buttons_pkey PRIMARY KEY (id),
  CONSTRAINT category_image_buttons_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_image_buttons_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.category_page_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  section_type text NOT NULL CHECK (section_type = ANY (ARRAY['banner'::text, 'product_grid'::text, 'featured_products'::text, 'bestsellers'::text, 'new_products'::text, 'recommended'::text])),
  title text,
  subtitle text,
  description text,
  image_url text,
  background_color text DEFAULT '#ffffff'::text,
  text_color text DEFAULT '#000000'::text,
  link_type text CHECK (link_type = ANY (ARRAY['category'::text, 'brand'::text, 'url'::text, 'tag'::text])),
  link_category_id uuid,
  link_brand_id uuid,
  link_url text,
  product_filter_type text CHECK (product_filter_type = ANY (ARRAY['manual'::text, 'category'::text, 'brand'::text, 'tag'::text, 'price_range'::text])),
  filter_category_id uuid,
  filter_brand_id uuid,
  filter_tags ARRAY,
  min_price numeric,
  max_price numeric,
  product_limit integer DEFAULT 10,
  display_style text DEFAULT 'grid'::text CHECK (display_style = ANY (ARRAY['grid'::text, 'horizontal_scroll'::text, 'list'::text])),
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  show_on_mobile boolean DEFAULT true,
  show_on_desktop boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT category_page_sections_pkey PRIMARY KEY (id),
  CONSTRAINT category_page_sections_filter_category_id_fkey FOREIGN KEY (filter_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_page_sections_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_page_sections_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT category_page_sections_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id),
  CONSTRAINT category_page_sections_filter_brand_id_fkey FOREIGN KEY (filter_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.category_section_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section_id uuid,
  product_id uuid,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT category_section_products_pkey PRIMARY KEY (id),
  CONSTRAINT category_section_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT category_section_products_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.category_page_sections(id)
);
CREATE TABLE public.grid_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  image_url text NOT NULL,
  mobile_image_url text,
  link_type text NOT NULL CHECK (link_type = ANY (ARRAY['category'::text, 'brand'::text, 'tag'::text, 'custom'::text])),
  link_category_id uuid,
  link_brand_id uuid,
  link_tag text,
  link_url text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT grid_banners_pkey PRIMARY KEY (id),
  CONSTRAINT grid_banners_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT grid_banners_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.hero_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  subtitle character varying,
  description text,
  image_url text NOT NULL,
  mobile_image_url text,
  link_url text,
  link_text character varying,
  background_color character varying DEFAULT '#ffffff'::character varying,
  text_color character varying DEFAULT '#000000'::character varying,
  button_color character varying DEFAULT '#e91e63'::character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  link_type character varying DEFAULT 'url'::character varying CHECK (link_type::text = ANY (ARRAY['category'::character varying, 'brand'::character varying, 'url'::character varying, 'tag'::character varying]::text[])),
  link_category_id uuid,
  link_brand_id uuid,
  CONSTRAINT hero_banners_pkey PRIMARY KEY (id),
  CONSTRAINT hero_banners_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT hero_banners_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  total numeric NOT NULL CHECK (total >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_number character varying NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'processing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  shipping_address_id uuid NOT NULL,
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_method character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'AFN'::character varying,
  payment_method character varying NOT NULL,
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  transaction_id character varying,
  gateway_response jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.positioned_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  subtitle character varying,
  description text,
  image_url text NOT NULL,
  mobile_image_url text,
  link_url text,
  link_text character varying,
  link_type character varying NOT NULL DEFAULT 'custom'::character varying CHECK (link_type::text = ANY (ARRAY['category'::character varying, 'brand'::character varying, 'custom'::character varying, 'tag'::character varying]::text[])),
  link_category_id uuid,
  link_brand_id uuid,
  link_tag character varying,
  background_color character varying DEFAULT '#ffffff'::character varying,
  text_color character varying DEFAULT '#000000'::character varying,
  button_color character varying DEFAULT '#e91e63'::character varying,
  position character varying NOT NULL CHECK ("position"::text = ANY (ARRAY['home_middle_1'::character varying, 'home_middle_2'::character varying, 'home_special'::character varying, 'home_bottom_1'::character varying, 'home_bottom_2'::character varying]::text[])),
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT positioned_banners_pkey PRIMARY KEY (id),
  CONSTRAINT positioned_banners_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT positioned_banners_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.product_attributes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  attribute_id uuid,
  attribute_value_id uuid,
  custom_value text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_attributes_pkey PRIMARY KEY (id),
  CONSTRAINT product_attributes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_attributes_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.attributes(id),
  CONSTRAINT product_attributes_attribute_value_id_fkey FOREIGN KEY (attribute_value_id) REFERENCES public.attribute_values(id)
);
CREATE TABLE public.product_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  brand_id uuid,
  category_id uuid,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_types_pkey PRIMARY KEY (id),
  CONSTRAINT product_types_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories_new(id),
  CONSTRAINT product_types_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  image_urls ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  category text,
  brand text,
  main_category_id uuid,
  sub_category_id uuid,
  brand_id uuid,
  short_description text,
  compare_price numeric,
  sku character varying,
  barcode character varying,
  weight numeric,
  length numeric,
  width numeric,
  height numeric,
  stock_quantity integer DEFAULT 0,
  min_stock_level integer DEFAULT 0,
  tags ARRAY,
  seo_title character varying,
  seo_description text,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  is_on_sale boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  category_id uuid,
  is_bestseller boolean DEFAULT false,
  sales_count integer DEFAULT 0,
  product_type_id uuid,
  is_recommended boolean DEFAULT false,
  is_new boolean DEFAULT false,
  stock_tracking_link text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_product_type_id_fkey FOREIGN KEY (product_type_id) REFERENCES public.product_types(id),
  CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories_new(id)
);
CREATE TABLE public.quick_access_buttons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  link_url character varying NOT NULL,
  link_type character varying NOT NULL CHECK (link_type::text = ANY (ARRAY['category'::character varying, 'brand'::character varying, 'custom'::character varying, 'tag'::character varying]::text[])),
  link_category_id uuid,
  link_brand_id uuid,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  link_tag character varying,
  CONSTRAINT quick_access_buttons_pkey PRIMARY KEY (id),
  CONSTRAINT quick_access_buttons_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT quick_access_buttons_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.secondary_hero_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subtitle text,
  description text,
  image_url text NOT NULL,
  mobile_image_url text,
  link_url text NOT NULL,
  link_text text,
  link_type text NOT NULL CHECK (link_type = ANY (ARRAY['category'::text, 'brand'::text, 'custom'::text, 'tag'::text])),
  link_category_id uuid,
  link_brand_id uuid,
  link_tag text,
  background_color text NOT NULL DEFAULT '#ffffff'::text,
  text_color text NOT NULL DEFAULT '#000000'::text,
  button_color text NOT NULL DEFAULT '#e91e63'::text,
  sort_order integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT secondary_hero_banners_pkey PRIMARY KEY (id),
  CONSTRAINT secondary_hero_banners_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id),
  CONSTRAINT secondary_hero_banners_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id)
);
CREATE TABLE public.simple_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  product_name character varying NOT NULL,
  product_image_url text,
  unit_price numeric NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT simple_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT simple_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT simple_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.simple_orders(id)
);
CREATE TABLE public.simple_order_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  old_status character varying,
  new_status character varying NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT simple_order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT simple_order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.simple_orders(id),
  CONSTRAINT simple_order_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.simple_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  subtotal numeric NOT NULL,
  shipping_cost numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  shipping_address jsonb NOT NULL,
  payment_method character varying,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  customer_notes text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT simple_orders_pkey PRIMARY KEY (id),
  CONSTRAINT simple_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.temp_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  temp_order_ref text NOT NULL UNIQUE,
  cart_data jsonb,
  shipping_address jsonb,
  customer_notes text DEFAULT ''::text,
  total_amount numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '02:00:00'::interval),
  customer_email character varying NOT NULL,
  items jsonb,
  shipping_info jsonb,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'expired'::character varying]::text[])),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT temp_orders_pkey PRIMARY KEY (id),
  CONSTRAINT temp_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.top_brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  image_url text NOT NULL,
  brand_id uuid NOT NULL,
  link_type character varying DEFAULT 'brand'::character varying CHECK (link_type::text = ANY (ARRAY['category'::character varying::text, 'brand'::character varying::text, 'url'::character varying::text, 'tag'::character varying::text])),
  link_category_id uuid,
  link_brand_id uuid,
  link_url text,
  link_tag character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT top_brands_pkey PRIMARY KEY (id),
  CONSTRAINT top_brands_link_brand_id_fkey FOREIGN KEY (link_brand_id) REFERENCES public.brands(id),
  CONSTRAINT top_brands_link_category_id_fkey FOREIGN KEY (link_category_id) REFERENCES public.categories_new(id),
  CONSTRAINT top_brands_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  user_type text NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);